# Generated by Django 2.2.6 on 2019-10-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DustBin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'plastic'), ('M', 'metal'), ('O', 'others')], max_length=1)),
                ('level', models.IntegerField()),
                ('date_time', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
