# Generated by Django 2.2.6 on 2019-10-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbin',
            name='has_been_emptied',
            field=models.BooleanField(default=False),
        ),
    ]
